# Form implementation generated from reading ui file 'EphemMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 2)
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 6, 0, 1, 1)
        self.LowellLogo = QtWidgets.QLabel(parent=self.centralwidget)
        self.LowellLogo.setText("")
        self.LowellLogo.setPixmap(QtGui.QPixmap("lowelllogo_horizontal_web.png"))
        self.LowellLogo.setObjectName("LowellLogo")
        self.gridLayout.addWidget(self.LowellLogo, 0, 0, 1, 1)
        self.sourceAstorb = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.sourceAstorb.setObjectName("sourceAstorb")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.sourceAstorb)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sourceHorizons = QtWidgets.QRadioButton(parent=self.sourceAstorb)
        self.sourceHorizons.setObjectName("sourceHorizons")
        self.horizontalLayout.addWidget(self.sourceHorizons)
        self.sourceScout = QtWidgets.QRadioButton(parent=self.sourceAstorb)
        self.sourceScout.setObjectName("sourceScout")
        self.horizontalLayout.addWidget(self.sourceScout)
        self.sourceMPC = QtWidgets.QRadioButton(parent=self.sourceAstorb)
        self.sourceMPC.setObjectName("sourceMPC")
        self.horizontalLayout.addWidget(self.sourceMPC)
        self.sourceNORAD = QtWidgets.QRadioButton(parent=self.sourceAstorb)
        self.sourceNORAD.setObjectName("sourceNORAD")
        self.horizontalLayout.addWidget(self.sourceNORAD)
        self.radioButton_5 = QtWidgets.QRadioButton(parent=self.sourceAstorb)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout.addWidget(self.radioButton_5)
        self.sourceIMCCE = QtWidgets.QRadioButton(parent=self.sourceAstorb)
        self.sourceIMCCE.setObjectName("sourceIMCCE")
        self.horizontalLayout.addWidget(self.sourceIMCCE)
        self.gridLayout.addWidget(self.sourceAstorb, 1, 0, 4, 5)
        self.exitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exitButton.setObjectName("exitButton")
        self.gridLayout.addWidget(self.exitButton, 7, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Objects"))
        self.label_2.setText(_translate("MainWindow", "LDT Ephemeris Generator"))
        self.sourceAstorb.setTitle(_translate("MainWindow", "Database Source"))
        self.sourceHorizons.setText(_translate("MainWindow", "JPL Horizons"))
        self.sourceScout.setText(_translate("MainWindow", "JPL Scout"))
        self.sourceMPC.setText(_translate("MainWindow", "Minor Planet Center"))
        self.sourceNORAD.setText(_translate("MainWindow", "NORAD"))
        self.radioButton_5.setText(_translate("MainWindow", "Astorb"))
        self.sourceIMCCE.setText(_translate("MainWindow", "IMCCE"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
