# Form implementation generated from reading ui file 'EphemMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EphemMainWindow(object):
    def setupUi(self, EphemMainWindow):
        EphemMainWindow.setObjectName("EphemMainWindow")
        EphemMainWindow.resize(837, 600)
        self.centralwidget = QtWidgets.QWidget(parent=EphemMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.LowellLogo = QtWidgets.QLabel(parent=self.centralwidget)
        self.LowellLogo.setText("")
        self.LowellLogo.setPixmap(QtGui.QPixmap("lowelllogo_horizontal_web.png"))
        self.LowellLogo.setObjectName("LowellLogo")
        self.gridLayout.addWidget(self.LowellLogo, 0, 0, 1, 1)
        self.sourceGroupbox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.sourceGroupbox.setObjectName("sourceGroupbox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.sourceGroupbox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sourceHorizons = QtWidgets.QRadioButton(parent=self.sourceGroupbox)
        self.sourceHorizons.setChecked(True)
        self.sourceHorizons.setObjectName("sourceHorizons")
        self.horizontalLayout.addWidget(self.sourceHorizons)
        self.sourceScout = QtWidgets.QRadioButton(parent=self.sourceGroupbox)
        self.sourceScout.setObjectName("sourceScout")
        self.horizontalLayout.addWidget(self.sourceScout)
        self.sourceMPC = QtWidgets.QRadioButton(parent=self.sourceGroupbox)
        self.sourceMPC.setObjectName("sourceMPC")
        self.horizontalLayout.addWidget(self.sourceMPC)
        self.sourceNORAD = QtWidgets.QRadioButton(parent=self.sourceGroupbox)
        self.sourceNORAD.setObjectName("sourceNORAD")
        self.horizontalLayout.addWidget(self.sourceNORAD)
        self.sourceAstorb = QtWidgets.QRadioButton(parent=self.sourceGroupbox)
        self.sourceAstorb.setObjectName("sourceAstorb")
        self.horizontalLayout.addWidget(self.sourceAstorb)
        self.sourceIMCCE = QtWidgets.QRadioButton(parent=self.sourceGroupbox)
        self.sourceIMCCE.setObjectName("sourceIMCCE")
        self.horizontalLayout.addWidget(self.sourceIMCCE)
        self.gridLayout.addWidget(self.sourceGroupbox, 1, 0, 1, 4)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 3, 1, 1)
        self.optionsBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.optionsBox.setTitle("")
        self.optionsBox.setObjectName("optionsBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.optionsBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(parent=self.optionsBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.inputStepSize = QtWidgets.QDoubleSpinBox(parent=self.optionsBox)
        self.inputStepSize.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.inputStepSize.setDecimals(1)
        self.inputStepSize.setMinimum(0.5)
        self.inputStepSize.setMaximum(120.0)
        self.inputStepSize.setProperty("value", 30.0)
        self.inputStepSize.setObjectName("inputStepSize")
        self.gridLayout_2.addWidget(self.inputStepSize, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.optionsBox)
        self.label_5.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.inputUTStart = QtWidgets.QDateTimeEdit(parent=self.optionsBox)
        self.inputUTStart.setDateTime(
            QtCore.QDateTime(QtCore.QDate(2015, 1, 2), QtCore.QTime(4, 0, 0))
        )
        self.inputUTStart.setMaximumDate(QtCore.QDate(2061, 1, 1))
        self.inputUTStart.setMinimumDate(QtCore.QDate(2015, 1, 1))
        self.inputUTStart.setMaximumTime(QtCore.QTime(15, 59, 59))
        self.inputUTStart.setCurrentSection(
            QtWidgets.QDateTimeEdit.Section.MonthSection
        )
        self.inputUTStart.setCalendarPopup(True)
        self.inputUTStart.setTimeSpec(QtCore.Qt.TimeSpec.UTC)
        self.inputUTStart.setObjectName("inputUTStart")
        self.gridLayout_2.addWidget(self.inputUTStart, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.optionsBox)
        self.label_4.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.optionsBox)
        self.label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.inputRefFrame = QtWidgets.QComboBox(parent=self.optionsBox)
        self.inputRefFrame.setObjectName("inputRefFrame")
        self.inputRefFrame.addItem("")
        self.inputRefFrame.addItem("")
        self.inputRefFrame.addItem("")
        self.gridLayout_2.addWidget(self.inputRefFrame, 3, 1, 1, 1)
        self.generateSelectedButton = QtWidgets.QPushButton(parent=self.optionsBox)
        self.generateSelectedButton.setObjectName("generateSelectedButton")
        self.gridLayout_2.addWidget(self.generateSelectedButton, 4, 0, 1, 2)
        self.inputUTEnd = QtWidgets.QDateTimeEdit(parent=self.optionsBox)
        self.inputUTEnd.setCurrentSection(QtWidgets.QDateTimeEdit.Section.MonthSection)
        self.inputUTEnd.setCalendarPopup(True)
        self.inputUTEnd.setTimeSpec(QtCore.Qt.TimeSpec.UTC)
        self.inputUTEnd.setObjectName("inputUTEnd")
        self.gridLayout_2.addWidget(self.inputUTEnd, 1, 1, 1, 1)
        self.generateAllButton = QtWidgets.QPushButton(parent=self.optionsBox)
        self.generateAllButton.setObjectName("generateAllButton")
        self.gridLayout_2.addWidget(self.generateAllButton, 5, 0, 1, 2)
        self.gridLayout.addWidget(self.optionsBox, 3, 3, 2, 1)
        self.addObjectsButton = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.addObjectsButton.sizePolicy().hasHeightForWidth()
        )
        self.addObjectsButton.setSizePolicy(sizePolicy)
        self.addObjectsButton.setMinimumSize(QtCore.QSize(150, 0))
        self.addObjectsButton.setCheckable(False)
        self.addObjectsButton.setObjectName("addObjectsButton")
        self.gridLayout.addWidget(self.addObjectsButton, 4, 0, 1, 1)
        self.removeObjectsButton = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.removeObjectsButton.sizePolicy().hasHeightForWidth()
        )
        self.removeObjectsButton.setSizePolicy(sizePolicy)
        self.removeObjectsButton.setMinimumSize(QtCore.QSize(150, 0))
        self.removeObjectsButton.setObjectName("removeObjectsButton")
        self.gridLayout.addWidget(self.removeObjectsButton, 4, 1, 1, 1)
        self.sortButton = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sortButton.sizePolicy().hasHeightForWidth())
        self.sortButton.setSizePolicy(sizePolicy)
        self.sortButton.setMinimumSize(QtCore.QSize(150, 0))
        self.sortButton.setObjectName("sortButton")
        self.gridLayout.addWidget(self.sortButton, 4, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.viewButton = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewButton.sizePolicy().hasHeightForWidth())
        self.viewButton.setSizePolicy(sizePolicy)
        self.viewButton.setMinimumSize(QtCore.QSize(150, 0))
        self.viewButton.setObjectName("viewButton")
        self.gridLayout.addWidget(self.viewButton, 7, 0, 1, 1)
        self.saveGeneratedButton = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.saveGeneratedButton.sizePolicy().hasHeightForWidth()
        )
        self.saveGeneratedButton.setSizePolicy(sizePolicy)
        self.saveGeneratedButton.setMinimumSize(QtCore.QSize(150, 0))
        self.saveGeneratedButton.setObjectName("saveGeneratedButton")
        self.gridLayout.addWidget(self.saveGeneratedButton, 7, 1, 1, 1)
        self.exitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exitButton.setObjectName("exitButton")
        self.gridLayout.addWidget(self.exitButton, 7, 3, 1, 1)
        self.objectList = QtWidgets.QListWidget(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.objectList.setFont(font)
        self.objectList.setAlternatingRowColors(True)
        self.objectList.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.MultiSelection
        )
        self.objectList.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows
        )
        self.objectList.setItemAlignment(QtCore.Qt.AlignmentFlag.AlignLeading)
        self.objectList.setObjectName("objectList")
        self.gridLayout.addWidget(self.objectList, 3, 0, 1, 3)
        self.labelTitle = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.labelTitle.setFont(font)
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.gridLayout.addWidget(self.labelTitle, 0, 1, 1, 3)
        self.labelStatus = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelStatus.setObjectName("labelStatus")
        self.gridLayout.addWidget(self.labelStatus, 6, 0, 1, 4)
        EphemMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=EphemMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 837, 24))
        self.menubar.setObjectName("menubar")
        EphemMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=EphemMainWindow)
        self.statusbar.setObjectName("statusbar")
        EphemMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(EphemMainWindow)
        QtCore.QMetaObject.connectSlotsByName(EphemMainWindow)
        EphemMainWindow.setTabOrder(self.sourceHorizons, self.sourceScout)
        EphemMainWindow.setTabOrder(self.sourceScout, self.sourceMPC)
        EphemMainWindow.setTabOrder(self.sourceMPC, self.sourceNORAD)
        EphemMainWindow.setTabOrder(self.sourceNORAD, self.sourceAstorb)
        EphemMainWindow.setTabOrder(self.sourceAstorb, self.sourceIMCCE)
        EphemMainWindow.setTabOrder(self.sourceIMCCE, self.objectList)
        EphemMainWindow.setTabOrder(self.objectList, self.addObjectsButton)
        EphemMainWindow.setTabOrder(self.addObjectsButton, self.removeObjectsButton)
        EphemMainWindow.setTabOrder(self.removeObjectsButton, self.sortButton)
        EphemMainWindow.setTabOrder(self.sortButton, self.inputUTStart)
        EphemMainWindow.setTabOrder(self.inputUTStart, self.inputUTEnd)
        EphemMainWindow.setTabOrder(self.inputUTEnd, self.inputStepSize)
        EphemMainWindow.setTabOrder(self.inputStepSize, self.inputRefFrame)
        EphemMainWindow.setTabOrder(self.inputRefFrame, self.generateSelectedButton)
        EphemMainWindow.setTabOrder(self.generateSelectedButton, self.generateAllButton)
        EphemMainWindow.setTabOrder(self.generateAllButton, self.viewButton)
        EphemMainWindow.setTabOrder(self.viewButton, self.saveGeneratedButton)
        EphemMainWindow.setTabOrder(self.saveGeneratedButton, self.exitButton)

    def retranslateUi(self, EphemMainWindow):
        _translate = QtCore.QCoreApplication.translate
        EphemMainWindow.setWindowTitle(
            _translate("EphemMainWindow", "LDT Ephemeris Generator Main Window")
        )
        self.sourceGroupbox.setTitle(_translate("EphemMainWindow", "Database Source"))
        self.sourceHorizons.setText(_translate("EphemMainWindow", "JPL Horizons"))
        self.sourceScout.setText(_translate("EphemMainWindow", "JPL Scout"))
        self.sourceMPC.setText(_translate("EphemMainWindow", "Minor Planet Center"))
        self.sourceNORAD.setText(_translate("EphemMainWindow", "NORAD"))
        self.sourceAstorb.setText(_translate("EphemMainWindow", "Astorb"))
        self.sourceIMCCE.setText(_translate("EphemMainWindow", "IMCCE"))
        self.label_3.setText(_translate("EphemMainWindow", "Objects :"))
        self.label_7.setText(_translate("EphemMainWindow", "Ephemeris Options :"))
        self.label_6.setText(_translate("EphemMainWindow", "Step Size (min) :"))
        self.label_5.setText(_translate("EphemMainWindow", "UT End :"))
        self.inputUTStart.setDisplayFormat(
            _translate("EphemMainWindow", "MM/dd/yyyy hh:mm")
        )
        self.label_4.setText(_translate("EphemMainWindow", "UT Start :"))
        self.label.setText(_translate("EphemMainWindow", "Reference Frame :"))
        self.inputRefFrame.setItemText(0, _translate("EphemMainWindow", "FK5 / J2000"))
        self.inputRefFrame.setItemText(1, _translate("EphemMainWindow", "ICRS / ICRF"))
        self.inputRefFrame.setItemText(2, _translate("EphemMainWindow", "Apparent"))
        self.generateSelectedButton.setText(
            _translate("EphemMainWindow", "Generate Selected Ephemeris")
        )
        self.inputUTEnd.setDisplayFormat(
            _translate("EphemMainWindow", "MM/dd/yyyy hh:mm")
        )
        self.generateAllButton.setText(
            _translate("EphemMainWindow", "Generate All Ephemerides")
        )
        self.addObjectsButton.setText(_translate("EphemMainWindow", "Add Objects"))
        self.removeObjectsButton.setText(
            _translate("EphemMainWindow", "Remove Objects")
        )
        self.sortButton.setText(_translate("EphemMainWindow", "Manual Sort"))
        self.label_2.setText(_translate("EphemMainWindow", "Status :"))
        self.viewButton.setText(_translate("EphemMainWindow", "View Selected"))
        self.saveGeneratedButton.setText(
            _translate("EphemMainWindow", "Save Generated to TCS")
        )
        self.exitButton.setText(_translate("EphemMainWindow", "Exit"))
        self.objectList.setSortingEnabled(True)
        self.labelTitle.setText(
            _translate("EphemMainWindow", "LDT Ephemeris Generator")
        )
        self.labelStatus.setText(_translate("EphemMainWindow", "Idle"))
