# Form implementation generated from reading ui file 'obstools/UI/ETCDataWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ETCDataWindow(object):
    def setupUi(self, ETCDataWindow):
        ETCDataWindow.setObjectName("ETCDataWindow")
        ETCDataWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(parent=ETCDataWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableDatalog = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableDatalog.setObjectName("tableDatalog")
        self.tableDatalog.setColumnCount(0)
        self.tableDatalog.setRowCount(0)
        self.verticalLayout.addWidget(self.tableDatalog)
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonRemoverow = QtWidgets.QPushButton(parent=self.groupBox)
        self.buttonRemoverow.setObjectName("buttonRemoverow")
        self.horizontalLayout.addWidget(self.buttonRemoverow)
        self.buttonCleartable = QtWidgets.QPushButton(parent=self.groupBox)
        self.buttonCleartable.setObjectName("buttonCleartable")
        self.horizontalLayout.addWidget(self.buttonCleartable)
        self.buttonSavetable = QtWidgets.QPushButton(parent=self.groupBox)
        self.buttonSavetable.setObjectName("buttonSavetable")
        self.horizontalLayout.addWidget(self.buttonSavetable)
        self.verticalLayout.addWidget(self.groupBox)
        ETCDataWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ETCDataWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 24))
        self.menubar.setObjectName("menubar")
        ETCDataWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ETCDataWindow)
        self.statusbar.setObjectName("statusbar")
        ETCDataWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ETCDataWindow)
        QtCore.QMetaObject.connectSlotsByName(ETCDataWindow)

    def retranslateUi(self, ETCDataWindow):
        _translate = QtCore.QCoreApplication.translate
        ETCDataWindow.setWindowTitle(_translate("ETCDataWindow", "MainWindow"))
        self.buttonRemoverow.setText(
            _translate("ETCDataWindow", "Remove Highlighted Row")
        )
        self.buttonCleartable.setText(_translate("ETCDataWindow", "Clear Table"))
        self.buttonSavetable.setText(_translate("ETCDataWindow", "Save Table"))
