# Form implementation generated from reading ui file 'UI/ETCDataWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ETCDataWindow(object):
    def setupUi(self, ETCDataWindow):
        ETCDataWindow.setObjectName("ETCDataWindow")
        ETCDataWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(parent=ETCDataWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonSavetable = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buttonSavetable.setObjectName("buttonSavetable")
        self.gridLayout.addWidget(self.buttonSavetable, 1, 3, 1, 1)
        self.buttonRemoverow = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buttonRemoverow.setObjectName("buttonRemoverow")
        self.gridLayout.addWidget(self.buttonRemoverow, 1, 1, 1, 1)
        self.buttonCleartable = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buttonCleartable.setObjectName("buttonCleartable")
        self.gridLayout.addWidget(self.buttonCleartable, 1, 2, 1, 1)
        self.tableDatalog = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableDatalog.setObjectName("tableDatalog")
        self.tableDatalog.setColumnCount(0)
        self.tableDatalog.setRowCount(0)
        self.gridLayout.addWidget(self.tableDatalog, 0, 1, 1, 3)
        ETCDataWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ETCDataWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 24))
        self.menubar.setObjectName("menubar")
        ETCDataWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ETCDataWindow)
        self.statusbar.setObjectName("statusbar")
        ETCDataWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ETCDataWindow)
        QtCore.QMetaObject.connectSlotsByName(ETCDataWindow)

    def retranslateUi(self, ETCDataWindow):
        _translate = QtCore.QCoreApplication.translate
        ETCDataWindow.setWindowTitle(_translate("ETCDataWindow", "ETC Data Table"))
        self.buttonSavetable.setText(_translate("ETCDataWindow", "Save Table"))
        self.buttonRemoverow.setText(
            _translate("ETCDataWindow", "Remove Highlighted Row")
        )
        self.buttonCleartable.setText(_translate("ETCDataWindow", "Clear Table"))
