# Form implementation generated from reading ui file 'obstools/UI/ETCDataWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ETCDataWindow(object):
    def setupUi(self, ETCDataWindow):
        ETCDataWindow.setObjectName("ETCDataWindow")
        ETCDataWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(parent=ETCDataWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.groupBox)
        ETCDataWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ETCDataWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 24))
        self.menubar.setObjectName("menubar")
        ETCDataWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ETCDataWindow)
        self.statusbar.setObjectName("statusbar")
        ETCDataWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ETCDataWindow)
        QtCore.QMetaObject.connectSlotsByName(ETCDataWindow)

    def retranslateUi(self, ETCDataWindow):
        _translate = QtCore.QCoreApplication.translate
        ETCDataWindow.setWindowTitle(_translate("ETCDataWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("ETCDataWindow", "Remove Highlighted Row"))
        self.pushButton_3.setText(_translate("ETCDataWindow", "Clear Table"))
        self.pushButton.setText(_translate("ETCDataWindow", "Save Table"))
