# Form implementation generated from reading ui file 'RIMAS2SlitMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 240)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.calculateButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.calculateButton.setObjectName("calculateButton")
        self.gridLayout.addWidget(self.calculateButton, 5, 0, 1, 1)
        self.centerXInput = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.centerXInput.setMinimum(1)
        self.centerXInput.setMaximum(4096)
        self.centerXInput.setProperty("value", 2037)
        self.centerXInput.setObjectName("centerXInput")
        self.gridLayout.addWidget(self.centerXInput, 1, 2, 1, 1)
        self.centerYInput = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.centerYInput.setMinimum(1)
        self.centerYInput.setMaximum(4096)
        self.centerYInput.setProperty("value", 1900)
        self.centerYInput.setObjectName("centerYInput")
        self.gridLayout.addWidget(self.centerYInput, 1, 3, 1, 1)
        self.LowellLogo = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LowellLogo.sizePolicy().hasHeightForWidth())
        self.LowellLogo.setSizePolicy(sizePolicy)
        self.LowellLogo.setMinimumSize(QtCore.QSize(0, 75))
        self.LowellLogo.setMaximumSize(QtCore.QSize(16777215, 50))
        self.LowellLogo.setText("")
        self.LowellLogo.setPixmap(
            QtGui.QPixmap(
                "../../../ldt_boresight/boresight/bdto/UI/lowelllogo_horizontal_web.png"
            )
        )
        self.LowellLogo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LowellLogo.setObjectName("LowellLogo")
        self.gridLayout.addWidget(self.LowellLogo, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.currentYInput = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.currentYInput.setMinimum(1)
        self.currentYInput.setMaximum(4096)
        self.currentYInput.setProperty("value", 1900)
        self.currentYInput.setObjectName("currentYInput")
        self.gridLayout.addWidget(self.currentYInput, 3, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.currentXInput = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.currentXInput.setMinimum(1)
        self.currentXInput.setMaximum(4096)
        self.currentXInput.setProperty("value", 2037)
        self.currentXInput.setObjectName("currentXInput")
        self.gridLayout.addWidget(self.currentXInput, 3, 2, 1, 1)
        self.labelTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.gridLayout.addWidget(self.labelTitle, 0, 2, 1, 2)
        self.exitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exitButton.setObjectName("exitButton")
        self.gridLayout.addWidget(self.exitButton, 5, 2, 1, 2)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.xiOutput = QtWidgets.QLabel(parent=self.centralwidget)
        self.xiOutput.setObjectName("xiOutput")
        self.gridLayout.addWidget(self.xiOutput, 4, 2, 1, 1)
        self.etaOutput = QtWidgets.QLabel(parent=self.centralwidget)
        self.etaOutput.setObjectName("etaOutput")
        self.gridLayout.addWidget(self.etaOutput, 4, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.currentXInput, self.currentYInput)
        MainWindow.setTabOrder(self.currentYInput, self.calculateButton)
        MainWindow.setTabOrder(self.calculateButton, self.exitButton)
        MainWindow.setTabOrder(self.exitButton, self.centerXInput)
        MainWindow.setTabOrder(self.centerXInput, self.centerYInput)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.calculateButton.setText(_translate("MainWindow", "Calculate"))
        self.label_3.setText(_translate("MainWindow", "Current Position:"))
        self.label_2.setText(_translate("MainWindow", "Center of Slit:"))
        self.labelTitle.setText(_translate("MainWindow", "RIMAS Offset to Slit Tool"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
        self.label.setText(_translate("MainWindow", "Offset (xi,eta):"))
        self.xiOutput.setText(_translate("MainWindow", "---"))
        self.etaOutput.setText(_translate("MainWindow", "---"))
