# Form implementation generated from reading ui file 'obstools/ETCDataWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ETCDataWindow(object):
    def setupUi(self, ETCDataWindow):
        ETCDataWindow.setObjectName("ETCDataWindow")
        ETCDataWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(parent=ETCDataWindow)
        self.centralwidget.setObjectName("centralwidget")
        ETCDataWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ETCDataWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 24))
        self.menubar.setObjectName("menubar")
        ETCDataWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ETCDataWindow)
        self.statusbar.setObjectName("statusbar")
        ETCDataWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ETCDataWindow)
        QtCore.QMetaObject.connectSlotsByName(ETCDataWindow)

    def retranslateUi(self, ETCDataWindow):
        _translate = QtCore.QCoreApplication.translate
        ETCDataWindow.setWindowTitle(_translate("ETCDataWindow", "MainWindow"))
