# Form implementation generated from reading ui file 'obstools/ETCWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.modeSelector = QtWidgets.QGroupBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeSelector.sizePolicy().hasHeightForWidth())
        self.modeSelector.setSizePolicy(sizePolicy)
        self.modeSelector.setObjectName("modeSelector")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.modeSelector)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelMode = QtWidgets.QLabel(parent=self.modeSelector)
        self.labelMode.setEnabled(True)
        self.labelMode.setObjectName("labelMode")
        self.verticalLayout.addWidget(self.labelMode)
        self.radioExpSnMag = QtWidgets.QRadioButton(parent=self.modeSelector)
        self.radioExpSnMag.setChecked(True)
        self.radioExpSnMag.setObjectName("radioExpSnMag")
        self.verticalLayout.addWidget(self.radioExpSnMag)
        self.radioExpPkMag = QtWidgets.QRadioButton(parent=self.modeSelector)
        self.radioExpPkMag.setObjectName("radioExpPkMag")
        self.verticalLayout.addWidget(self.radioExpPkMag)
        self.radioSnExpMag = QtWidgets.QRadioButton(parent=self.modeSelector)
        self.radioSnExpMag.setObjectName("radioSnExpMag")
        self.verticalLayout.addWidget(self.radioSnExpMag)
        self.radioMagSnExp = QtWidgets.QRadioButton(parent=self.modeSelector)
        self.radioMagSnExp.setObjectName("radioMagSnExp")
        self.verticalLayout.addWidget(self.radioMagSnExp)
        self.gridLayout.addWidget(self.modeSelector, 0, 0, 1, 1)
        self.exitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exitButton.setObjectName("exitButton")
        self.gridLayout.addWidget(self.exitButton, 2, 1, 1, 1)
        self.otherOutputs = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.otherOutputs.setObjectName("otherOutputs")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.otherOutputs)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelNoisestar = QtWidgets.QLabel(parent=self.otherOutputs)
        self.labelNoisestar.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelNoisestar.setObjectName("labelNoisestar")
        self.gridLayout_3.addWidget(self.labelNoisestar, 4, 0, 1, 1)
        self.labelNpix = QtWidgets.QLabel(parent=self.otherOutputs)
        self.labelNpix.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelNpix.setObjectName("labelNpix")
        self.gridLayout_3.addWidget(self.labelNpix, 0, 0, 1, 1)
        self.labelNestar = QtWidgets.QLabel(parent=self.otherOutputs)
        self.labelNestar.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelNestar.setObjectName("labelNestar")
        self.gridLayout_3.addWidget(self.labelNestar, 2, 0, 1, 1)
        self.labelPeakestar = QtWidgets.QLabel(parent=self.otherOutputs)
        self.labelPeakestar.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelPeakestar.setObjectName("labelPeakestar")
        self.gridLayout_3.addWidget(self.labelPeakestar, 3, 0, 1, 1)
        self.outputNpix = QtWidgets.QLabel(parent=self.otherOutputs)
        self.outputNpix.setText("")
        self.outputNpix.setObjectName("outputNpix")
        self.gridLayout_3.addWidget(self.outputNpix, 0, 1, 1, 1)
        self.outputSkybright = QtWidgets.QLabel(parent=self.otherOutputs)
        self.outputSkybright.setText("")
        self.outputSkybright.setObjectName("outputSkybright")
        self.gridLayout_3.addWidget(self.outputSkybright, 1, 1, 1, 1)
        self.outputPeakestar = QtWidgets.QLabel(parent=self.otherOutputs)
        self.outputPeakestar.setText("")
        self.outputPeakestar.setObjectName("outputPeakestar")
        self.gridLayout_3.addWidget(self.outputPeakestar, 3, 1, 1, 1)
        self.labelSkybright = QtWidgets.QLabel(parent=self.otherOutputs)
        self.labelSkybright.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelSkybright.setObjectName("labelSkybright")
        self.gridLayout_3.addWidget(self.labelSkybright, 1, 0, 1, 1)
        self.outputNestar = QtWidgets.QLabel(parent=self.otherOutputs)
        self.outputNestar.setText("")
        self.outputNestar.setObjectName("outputNestar")
        self.gridLayout_3.addWidget(self.outputNestar, 2, 1, 1, 1)
        self.labelNoisesky = QtWidgets.QLabel(parent=self.otherOutputs)
        self.labelNoisesky.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelNoisesky.setObjectName("labelNoisesky")
        self.gridLayout_3.addWidget(self.labelNoisesky, 5, 0, 1, 1)
        self.labelNoiseccd = QtWidgets.QLabel(parent=self.otherOutputs)
        self.labelNoiseccd.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelNoiseccd.setObjectName("labelNoiseccd")
        self.gridLayout_3.addWidget(self.labelNoiseccd, 6, 0, 1, 1)
        self.outputNoisestar = QtWidgets.QLabel(parent=self.otherOutputs)
        self.outputNoisestar.setText("")
        self.outputNoisestar.setObjectName("outputNoisestar")
        self.gridLayout_3.addWidget(self.outputNoisestar, 4, 1, 1, 1)
        self.outputNoisesky = QtWidgets.QLabel(parent=self.otherOutputs)
        self.outputNoisesky.setText("")
        self.outputNoisesky.setObjectName("outputNoisesky")
        self.gridLayout_3.addWidget(self.outputNoisesky, 5, 1, 1, 1)
        self.outputNoiseccd = QtWidgets.QLabel(parent=self.otherOutputs)
        self.outputNoiseccd.setText("")
        self.outputNoiseccd.setObjectName("outputNoiseccd")
        self.gridLayout_3.addWidget(self.outputNoiseccd, 6, 1, 1, 1)
        self.gridLayout.addWidget(self.otherOutputs, 1, 1, 1, 1)
        self.keyOutputs = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.keyOutputs.setObjectName("keyOutputs")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.keyOutputs)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.outputBandpass = QtWidgets.QLabel(parent=self.keyOutputs)
        self.outputBandpass.setText("")
        self.outputBandpass.setObjectName("outputBandpass")
        self.gridLayout_2.addWidget(self.outputBandpass, 0, 1, 1, 1)
        self.labelBandpass = QtWidgets.QLabel(parent=self.keyOutputs)
        self.labelBandpass.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelBandpass.setObjectName("labelBandpass")
        self.gridLayout_2.addWidget(self.labelBandpass, 0, 0, 1, 1)
        self.labelExptime = QtWidgets.QLabel(parent=self.keyOutputs)
        self.labelExptime.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelExptime.setObjectName("labelExptime")
        self.gridLayout_2.addWidget(self.labelExptime, 3, 0, 1, 1)
        self.outputMagnitude = QtWidgets.QLabel(parent=self.keyOutputs)
        self.outputMagnitude.setText("")
        self.outputMagnitude.setObjectName("outputMagnitude")
        self.gridLayout_2.addWidget(self.outputMagnitude, 1, 1, 1, 1)
        self.labelMagnitude = QtWidgets.QLabel(parent=self.keyOutputs)
        self.labelMagnitude.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelMagnitude.setObjectName("labelMagnitude")
        self.gridLayout_2.addWidget(self.labelMagnitude, 1, 0, 1, 1)
        self.labelSNratio = QtWidgets.QLabel(parent=self.keyOutputs)
        self.labelSNratio.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelSNratio.setObjectName("labelSNratio")
        self.gridLayout_2.addWidget(self.labelSNratio, 2, 0, 1, 1)
        self.labelBinning = QtWidgets.QLabel(parent=self.keyOutputs)
        self.labelBinning.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelBinning.setObjectName("labelBinning")
        self.gridLayout_2.addWidget(self.labelBinning, 4, 0, 1, 1)
        self.outputSnratio = QtWidgets.QLabel(parent=self.keyOutputs)
        self.outputSnratio.setText("")
        self.outputSnratio.setObjectName("outputSnratio")
        self.gridLayout_2.addWidget(self.outputSnratio, 2, 1, 1, 1)
        self.outputExptime = QtWidgets.QLabel(parent=self.keyOutputs)
        self.outputExptime.setText("")
        self.outputExptime.setObjectName("outputExptime")
        self.gridLayout_2.addWidget(self.outputExptime, 3, 1, 1, 1)
        self.outputBinning = QtWidgets.QLabel(parent=self.keyOutputs)
        self.outputBinning.setText("")
        self.outputBinning.setObjectName("outputBinning")
        self.gridLayout_2.addWidget(self.outputBinning, 4, 1, 1, 1)
        self.gridLayout.addWidget(self.keyOutputs, 1, 0, 1, 1)
        self.inputBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.inputBox.setObjectName("inputBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.inputBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.modeInput = QtWidgets.QStackedWidget(parent=self.inputBox)
        self.modeInput.setObjectName("modeInput")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setMinimumSize(QtCore.QSize(0, 10))
        self.page_3.setObjectName("page_3")
        self.modeInput.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setMinimumSize(QtCore.QSize(0, 10))
        self.page_4.setObjectName("page_4")
        self.commonInput = QtWidgets.QWidget(parent=self.page_4)
        self.commonInput.setGeometry(QtCore.QRect(0, 30, 356, 204))
        self.commonInput.setObjectName("commonInput")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.commonInput)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.comboBox = QtWidgets.QComboBox(parent=self.commonInput)
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_4.addWidget(self.comboBox, 0, 2, 1, 1)
        self.inputLunarphase = QtWidgets.QComboBox(parent=self.commonInput)
        self.inputLunarphase.setObjectName("inputLunarphase")
        self.inputLunarphase.addItem("")
        self.inputLunarphase.addItem("")
        self.inputLunarphase.addItem("")
        self.inputLunarphase.addItem("")
        self.inputLunarphase.addItem("")
        self.inputLunarphase.addItem("")
        self.inputLunarphase.addItem("")
        self.inputLunarphase.addItem("")
        self.inputLunarphase.addItem("")
        self.inputLunarphase.addItem("")
        self.inputLunarphase.addItem("")
        self.inputLunarphase.addItem("")
        self.inputLunarphase.addItem("")
        self.inputLunarphase.addItem("")
        self.inputLunarphase.addItem("")
        self.gridLayout_4.addWidget(self.inputLunarphase, 4, 2, 1, 1)
        self.labelBinning_2 = QtWidgets.QLabel(parent=self.commonInput)
        self.labelBinning_2.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelBinning_2.setObjectName("labelBinning_2")
        self.gridLayout_4.addWidget(self.labelBinning_2, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.commonInput)
        self.label_5.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.labelSeeing = QtWidgets.QLabel(parent=self.commonInput)
        self.labelSeeing.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelSeeing.setObjectName("labelSeeing")
        self.gridLayout_4.addWidget(self.labelSeeing, 2, 0, 1, 1)
        self.labelAirmass = QtWidgets.QLabel(parent=self.commonInput)
        self.labelAirmass.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelAirmass.setObjectName("labelAirmass")
        self.gridLayout_4.addWidget(self.labelAirmass, 5, 0, 1, 1)
        self.inputAirmass = QtWidgets.QDoubleSpinBox(parent=self.commonInput)
        self.inputAirmass.setDecimals(1)
        self.inputAirmass.setMinimum(1.0)
        self.inputAirmass.setMaximum(2.4)
        self.inputAirmass.setSingleStep(0.2)
        self.inputAirmass.setObjectName("inputAirmass")
        self.gridLayout_4.addWidget(self.inputAirmass, 5, 2, 1, 1)
        self.inputBinning = QtWidgets.QSpinBox(parent=self.commonInput)
        self.inputBinning.setMinimum(1)
        self.inputBinning.setMaximum(4)
        self.inputBinning.setProperty("value", 2)
        self.inputBinning.setObjectName("inputBinning")
        self.gridLayout_4.addWidget(self.inputBinning, 1, 2, 1, 1)
        self.labelLunarphase = QtWidgets.QLabel(parent=self.commonInput)
        self.labelLunarphase.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelLunarphase.setObjectName("labelLunarphase")
        self.gridLayout_4.addWidget(self.labelLunarphase, 4, 0, 1, 1)
        self.inputSeeing = QtWidgets.QDoubleSpinBox(parent=self.commonInput)
        self.inputSeeing.setDecimals(1)
        self.inputSeeing.setMinimum(0.6)
        self.inputSeeing.setMaximum(2.4)
        self.inputSeeing.setSingleStep(0.2)
        self.inputSeeing.setProperty("value", 1.0)
        self.inputSeeing.setObjectName("inputSeeing")
        self.gridLayout_4.addWidget(self.inputSeeing, 2, 2, 1, 1)
        self.modeInput.addWidget(self.page_4)
        self.verticalLayout_2.addWidget(self.modeInput)
        self.gridLayout.addWidget(self.inputBox, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.modeInput.setCurrentIndex(1)
        self.comboBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(
            _translate("MainWindow", "LMI Exposure Time Calculator")
        )
        self.modeSelector.setTitle(_translate("MainWindow", "Mode Selector"))
        self.labelMode.setText(_translate("MainWindow", "ETC Mode:"))
        self.radioExpSnMag.setText(
            _translate("MainWindow", "Exposure time for a given S/N and magnitude")
        )
        self.radioExpPkMag.setText(
            _translate(
                "MainWindow", "Exposure time for a given peak counts and magnitude"
            )
        )
        self.radioSnExpMag.setText(
            _translate("MainWindow", "S/N for a given exposure time and magnitude")
        )
        self.radioMagSnExp.setText(
            _translate("MainWindow", "Magnitude for a given S/N and exposure time")
        )
        self.exitButton.setText(_translate("MainWindow", "Exit"))
        self.otherOutputs.setTitle(_translate("MainWindow", "Other Outputs"))
        self.labelNoisestar.setText(
            _translate("MainWindow", "Noise contribution (star) [e-] :")
        )
        self.labelNpix.setText(_translate("MainWindow", "Num pixels in aperture :"))
        self.labelNestar.setText(_translate("MainWindow", "Num e- from star :"))
        self.labelPeakestar.setText(_translate("MainWindow", "Peak e- from star :"))
        self.labelSkybright.setText(
            _translate("MainWindow", "Sky brightness (e-/pix) :")
        )
        self.labelNoisesky.setText(
            _translate("MainWindow", "Noise contribution (sky) [e-] :")
        )
        self.labelNoiseccd.setText(
            _translate("MainWindow", "Noise Contribution (CCD) [e-]:")
        )
        self.keyOutputs.setTitle(_translate("MainWindow", "Key Outputs"))
        self.labelBandpass.setText(_translate("MainWindow", "Bandpass :"))
        self.labelExptime.setText(_translate("MainWindow", "Exposure Time (s) :"))
        self.labelMagnitude.setText(_translate("MainWindow", "Magnitude :"))
        self.labelSNratio.setText(_translate("MainWindow", "S/N Ratio :"))
        self.labelBinning.setText(_translate("MainWindow", "Binning :"))
        self.inputBox.setTitle(_translate("MainWindow", "Inputs"))
        self.comboBox.setItemText(0, _translate("MainWindow", "U"))
        self.comboBox.setItemText(1, _translate("MainWindow", "B"))
        self.comboBox.setItemText(2, _translate("MainWindow", "V"))
        self.comboBox.setItemText(3, _translate("MainWindow", "R"))
        self.comboBox.setItemText(4, _translate("MainWindow", "I"))
        self.comboBox.setItemText(5, _translate("MainWindow", "VR"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Hα-On"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Hα-Off"))
        self.comboBox.setItemText(8, _translate("MainWindow", "[OIII]"))
        self.comboBox.setItemText(9, _translate("MainWindow", "WR"))
        self.comboBox.setItemText(10, _translate("MainWindow", "u'"))
        self.comboBox.setItemText(11, _translate("MainWindow", "g'"))
        self.comboBox.setItemText(12, _translate("MainWindow", "r'"))
        self.comboBox.setItemText(13, _translate("MainWindow", "i'"))
        self.comboBox.setItemText(14, _translate("MainWindow", "z'"))
        self.comboBox.setItemText(15, _translate("MainWindow", "yish"))
        self.inputLunarphase.setItemText(
            0, _translate("MainWindow", "0 (new moon)", "0")
        )
        self.inputLunarphase.setItemText(1, _translate("MainWindow", "1"))
        self.inputLunarphase.setItemText(2, _translate("MainWindow", "2"))
        self.inputLunarphase.setItemText(3, _translate("MainWindow", "3"))
        self.inputLunarphase.setItemText(4, _translate("MainWindow", "4"))
        self.inputLunarphase.setItemText(5, _translate("MainWindow", "5"))
        self.inputLunarphase.setItemText(6, _translate("MainWindow", "6"))
        self.inputLunarphase.setItemText(
            7, _translate("MainWindow", "7 (first/last quarter)", "7")
        )
        self.inputLunarphase.setItemText(8, _translate("MainWindow", "8"))
        self.inputLunarphase.setItemText(9, _translate("MainWindow", "9"))
        self.inputLunarphase.setItemText(10, _translate("MainWindow", "10"))
        self.inputLunarphase.setItemText(11, _translate("MainWindow", "11"))
        self.inputLunarphase.setItemText(12, _translate("MainWindow", "12"))
        self.inputLunarphase.setItemText(13, _translate("MainWindow", "13"))
        self.inputLunarphase.setItemText(
            14, _translate("MainWindow", "14 (full moon)", "14")
        )
        self.labelBinning_2.setText(_translate("MainWindow", "CCD Binning Factor :"))
        self.label_5.setText(_translate("MainWindow", "Bandpass :"))
        self.labelSeeing.setText(_translate("MainWindow", "Seeing (arcseconds) :"))
        self.labelAirmass.setText(_translate("MainWindow", "Airmass :"))
        self.labelLunarphase.setText(_translate("MainWindow", "Lunar Phase (days) :"))
