# Form implementation generated from reading ui file 'obstools/ETCWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.ExpSnMag = QtWidgets.QWidget()
        self.ExpSnMag.setObjectName("ExpSnMag")
        self.stackedWidget.addWidget(self.ExpSnMag)
        self.ExpPkMag = QtWidgets.QWidget()
        self.ExpPkMag.setObjectName("ExpPkMag")
        self.stackedWidget.addWidget(self.ExpPkMag)
        self.SnExpMag = QtWidgets.QWidget()
        self.SnExpMag.setObjectName("SnExpMag")
        self.stackedWidget.addWidget(self.SnExpMag)
        self.MagSnExp = QtWidgets.QWidget()
        self.MagSnExp.setObjectName("MagSnExp")
        self.stackedWidget.addWidget(self.MagSnExp)
        self.gridLayout.addWidget(self.stackedWidget, 0, 1, 1, 1)
        self.modeSelector = QtWidgets.QGroupBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeSelector.sizePolicy().hasHeightForWidth())
        self.modeSelector.setSizePolicy(sizePolicy)
        self.modeSelector.setObjectName("modeSelector")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.modeSelector)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelMode = QtWidgets.QLabel(parent=self.modeSelector)
        self.labelMode.setEnabled(True)
        self.labelMode.setObjectName("labelMode")
        self.verticalLayout.addWidget(self.labelMode)
        self.radioExpSnMag = QtWidgets.QRadioButton(parent=self.modeSelector)
        self.radioExpSnMag.setChecked(True)
        self.radioExpSnMag.setObjectName("radioExpSnMag")
        self.verticalLayout.addWidget(self.radioExpSnMag)
        self.radioExpPkMag = QtWidgets.QRadioButton(parent=self.modeSelector)
        self.radioExpPkMag.setObjectName("radioExpPkMag")
        self.verticalLayout.addWidget(self.radioExpPkMag)
        self.radioSnExpMag = QtWidgets.QRadioButton(parent=self.modeSelector)
        self.radioSnExpMag.setObjectName("radioSnExpMag")
        self.verticalLayout.addWidget(self.radioSnExpMag)
        self.radioMagSnExp = QtWidgets.QRadioButton(parent=self.modeSelector)
        self.radioMagSnExp.setObjectName("radioMagSnExp")
        self.verticalLayout.addWidget(self.radioMagSnExp)
        self.gridLayout.addWidget(self.modeSelector, 0, 0, 1, 1)
        self.otherOutputs = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.otherOutputs.setObjectName("otherOutputs")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.otherOutputs)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelNoisestar = QtWidgets.QLabel(parent=self.otherOutputs)
        self.labelNoisestar.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelNoisestar.setObjectName("labelNoisestar")
        self.gridLayout_3.addWidget(self.labelNoisestar, 4, 0, 1, 1)
        self.labelNpix = QtWidgets.QLabel(parent=self.otherOutputs)
        self.labelNpix.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelNpix.setObjectName("labelNpix")
        self.gridLayout_3.addWidget(self.labelNpix, 0, 0, 1, 1)
        self.labelNestar = QtWidgets.QLabel(parent=self.otherOutputs)
        self.labelNestar.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelNestar.setObjectName("labelNestar")
        self.gridLayout_3.addWidget(self.labelNestar, 2, 0, 1, 1)
        self.labelPeakestar = QtWidgets.QLabel(parent=self.otherOutputs)
        self.labelPeakestar.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelPeakestar.setObjectName("labelPeakestar")
        self.gridLayout_3.addWidget(self.labelPeakestar, 3, 0, 1, 1)
        self.outputNpix = QtWidgets.QLabel(parent=self.otherOutputs)
        self.outputNpix.setText("")
        self.outputNpix.setObjectName("outputNpix")
        self.gridLayout_3.addWidget(self.outputNpix, 0, 1, 1, 1)
        self.outputSkybright = QtWidgets.QLabel(parent=self.otherOutputs)
        self.outputSkybright.setText("")
        self.outputSkybright.setObjectName("outputSkybright")
        self.gridLayout_3.addWidget(self.outputSkybright, 1, 1, 1, 1)
        self.outputPeakestar = QtWidgets.QLabel(parent=self.otherOutputs)
        self.outputPeakestar.setText("")
        self.outputPeakestar.setObjectName("outputPeakestar")
        self.gridLayout_3.addWidget(self.outputPeakestar, 3, 1, 1, 1)
        self.labelSkybright = QtWidgets.QLabel(parent=self.otherOutputs)
        self.labelSkybright.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelSkybright.setObjectName("labelSkybright")
        self.gridLayout_3.addWidget(self.labelSkybright, 1, 0, 1, 1)
        self.outputNestar = QtWidgets.QLabel(parent=self.otherOutputs)
        self.outputNestar.setText("")
        self.outputNestar.setObjectName("outputNestar")
        self.gridLayout_3.addWidget(self.outputNestar, 2, 1, 1, 1)
        self.labelNoisesky = QtWidgets.QLabel(parent=self.otherOutputs)
        self.labelNoisesky.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelNoisesky.setObjectName("labelNoisesky")
        self.gridLayout_3.addWidget(self.labelNoisesky, 5, 0, 1, 1)
        self.labelNoiseccd = QtWidgets.QLabel(parent=self.otherOutputs)
        self.labelNoiseccd.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelNoiseccd.setObjectName("labelNoiseccd")
        self.gridLayout_3.addWidget(self.labelNoiseccd, 6, 0, 1, 1)
        self.outputNoisestar = QtWidgets.QLabel(parent=self.otherOutputs)
        self.outputNoisestar.setText("")
        self.outputNoisestar.setObjectName("outputNoisestar")
        self.gridLayout_3.addWidget(self.outputNoisestar, 4, 1, 1, 1)
        self.outputNoisesky = QtWidgets.QLabel(parent=self.otherOutputs)
        self.outputNoisesky.setText("")
        self.outputNoisesky.setObjectName("outputNoisesky")
        self.gridLayout_3.addWidget(self.outputNoisesky, 5, 1, 1, 1)
        self.outputNoiseccd = QtWidgets.QLabel(parent=self.otherOutputs)
        self.outputNoiseccd.setText("")
        self.outputNoiseccd.setObjectName("outputNoiseccd")
        self.gridLayout_3.addWidget(self.outputNoiseccd, 6, 1, 1, 1)
        self.gridLayout.addWidget(self.otherOutputs, 1, 1, 1, 1)
        self.keyOutputs = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.keyOutputs.setObjectName("keyOutputs")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.keyOutputs)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.outputBandpass = QtWidgets.QLabel(parent=self.keyOutputs)
        self.outputBandpass.setText("")
        self.outputBandpass.setObjectName("outputBandpass")
        self.gridLayout_2.addWidget(self.outputBandpass, 0, 1, 1, 1)
        self.labelBandpass = QtWidgets.QLabel(parent=self.keyOutputs)
        self.labelBandpass.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelBandpass.setObjectName("labelBandpass")
        self.gridLayout_2.addWidget(self.labelBandpass, 0, 0, 1, 1)
        self.labelExptime = QtWidgets.QLabel(parent=self.keyOutputs)
        self.labelExptime.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelExptime.setObjectName("labelExptime")
        self.gridLayout_2.addWidget(self.labelExptime, 3, 0, 1, 1)
        self.outputMagnitude = QtWidgets.QLabel(parent=self.keyOutputs)
        self.outputMagnitude.setText("")
        self.outputMagnitude.setObjectName("outputMagnitude")
        self.gridLayout_2.addWidget(self.outputMagnitude, 1, 1, 1, 1)
        self.labelMagnitude = QtWidgets.QLabel(parent=self.keyOutputs)
        self.labelMagnitude.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelMagnitude.setObjectName("labelMagnitude")
        self.gridLayout_2.addWidget(self.labelMagnitude, 1, 0, 1, 1)
        self.labelSNratio = QtWidgets.QLabel(parent=self.keyOutputs)
        self.labelSNratio.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelSNratio.setObjectName("labelSNratio")
        self.gridLayout_2.addWidget(self.labelSNratio, 2, 0, 1, 1)
        self.labelBinning = QtWidgets.QLabel(parent=self.keyOutputs)
        self.labelBinning.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.labelBinning.setObjectName("labelBinning")
        self.gridLayout_2.addWidget(self.labelBinning, 4, 0, 1, 1)
        self.outputSnratio = QtWidgets.QLabel(parent=self.keyOutputs)
        self.outputSnratio.setText("")
        self.outputSnratio.setObjectName("outputSnratio")
        self.gridLayout_2.addWidget(self.outputSnratio, 2, 1, 1, 1)
        self.outputExptime = QtWidgets.QLabel(parent=self.keyOutputs)
        self.outputExptime.setText("")
        self.outputExptime.setObjectName("outputExptime")
        self.gridLayout_2.addWidget(self.outputExptime, 3, 1, 1, 1)
        self.outputBinning = QtWidgets.QLabel(parent=self.keyOutputs)
        self.outputBinning.setText("")
        self.outputBinning.setObjectName("outputBinning")
        self.gridLayout_2.addWidget(self.outputBinning, 4, 1, 1, 1)
        self.gridLayout.addWidget(self.keyOutputs, 1, 0, 1, 1)
        self.exitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exitButton.setObjectName("exitButton")
        self.gridLayout.addWidget(self.exitButton, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(
            _translate("MainWindow", "LMI Exposure Time Calculator")
        )
        self.modeSelector.setTitle(_translate("MainWindow", "Mode Selector"))
        self.labelMode.setText(_translate("MainWindow", "ETC Mode:"))
        self.radioExpSnMag.setText(
            _translate("MainWindow", "Exposure time for a given S/N and magnitude")
        )
        self.radioExpPkMag.setText(
            _translate(
                "MainWindow", "Exposure time for a given peak counts and magnitude"
            )
        )
        self.radioSnExpMag.setText(
            _translate("MainWindow", "S/N for a given exposure time and magnitude")
        )
        self.radioMagSnExp.setText(
            _translate("MainWindow", "Magnitude for a given S/N and exposure time")
        )
        self.otherOutputs.setTitle(_translate("MainWindow", "Other Outputs"))
        self.labelNoisestar.setText(
            _translate("MainWindow", "Noise contribution (star) [e-] :")
        )
        self.labelNpix.setText(_translate("MainWindow", "Num pixels in aperture :"))
        self.labelNestar.setText(_translate("MainWindow", "Num e- from star :"))
        self.labelPeakestar.setText(_translate("MainWindow", "Peak e- from star :"))
        self.labelSkybright.setText(
            _translate("MainWindow", "Sky brightness (e-/pix) :")
        )
        self.labelNoisesky.setText(
            _translate("MainWindow", "Noise contribution (sky) [e-] :")
        )
        self.labelNoiseccd.setText(
            _translate("MainWindow", "Noise Contribution (CCD) [e-]:")
        )
        self.keyOutputs.setTitle(_translate("MainWindow", "Key Outputs"))
        self.labelBandpass.setText(_translate("MainWindow", "Bandpass :"))
        self.labelExptime.setText(_translate("MainWindow", "Exposure Time (s) :"))
        self.labelMagnitude.setText(_translate("MainWindow", "Magnitude :"))
        self.labelSNratio.setText(_translate("MainWindow", "S/N Ratio :"))
        self.labelBinning.setText(_translate("MainWindow", "Binning :"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
